---
- hosts:
    - all
  pre_tasks:
    # instalacja dockera
    - name: execute install docker script
      ansible.builtin.script:
        cmd: ./install_docker.sh
      poll: 20
      # tworzenie sieci dockerowej dla kontenerów
    - name: create docker network
      community.docker.docker_network:
        name: wusnetwork

- hosts:
    - all
  roles:
    - database_primary

- hosts:
    - all
  roles:
    - database_secondary

- hosts:
    - all
  roles:
    - backend_replication

- hosts:
    - all
  roles:
    - backend_secondary

- hosts:
    - all
  roles:
    - loadbalancer

- hosts:
    - all
  roles:
    - frontend
